### ISSUE TITLE
a little guide

### ISSUE THREAD

**Issue by kenshiro75** [someburner/esp-rfm69#2]
hi,
i'm working on a project involving esp12e and rfm69hw and your library is very helpful, many thanks.
i've succeded in compiling it under cygwin in windows 7 and i've generated the user1.bin (265kb) and user2.bin (265kb) firmware's files.
now i don't understand how to correctly flash them into esp12e via a serial CP2102 TTL USB.
do i have to upload/flash the 2 files together ?
if so what is the order and the mem addresses  ? 
after uploaded them how do i access the wifi interface to see the messages ?

thank you very much!
Ken

**Comment by someburner** [comment]
As it is I believe it just flashes boot_v1.4(b1).bin to 0x00000 and user1 to 0x01000. So you should be able to get by with just those 2. I've switched the project over to use esp-ginx as a base and I'm going to be re-doing some of the flash read/write stuff, and it should be simpler after that. Stay tuned!

**Comment by someburner** [comment]
New version produces 2-3 bins, which must be written.
