### ISSUE TITLE
section `.text' will not fit in region `iram1_0_seg'

### ISSUE THREAD

**Issue by mharizanov** [someburner/esp-rfm69#4]
Hi,
great work, I've been doing similar project myself, this is much more advanced though. Decided to give it a try, but can't get it to compile; Pointers to fixing this?

/home/mharizanov/esp-open-sdk/xtensa-lx106-elf/bin/xtensa-lx106-elf-ar: creating .output/eagle/debug/lib/spiffs.a
/home/mharizanov/esp-open-sdk/xtensa-lx106-elf/lib/gcc/xtensa-lx106-elf/4.8.5/../../../../xtensa-lx106-elf/bin/ld: .output/eagle/debug/image/eagle.app.v6.out section `.text' will not fit in region`iram1_0_seg'

**Comment by someburner** [comment]
Anything after 1.5.2 (I think) Espressif made more use of IRAM and I had to revert some of the attributes. Let me know what version SDK you're using and I'll make a quick edit

**Comment by mharizanov** [comment]
Running 1.5.4

**Comment by someburner** [comment]
Try the new branch I just made: 
https://github.com/someburner/esp-rfm69/tree/sdk-1.5.3%2B

I haven't tested it, but it _should_ work. Uart will be slower, but probably not noticeably so.

**Comment by mharizanov** [comment]
It compiled, thanks. I'll give it a try now.
